version: '3'
services:
  mysql:
    container_name: task_manager_mysql
    image: mysql:latest
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: hometaskmanager